### PR TITLE
Milestone : Project #8 Completed [Build Custom Framework]

### PR DESCRIPTION
**Pull request by simondebbarma**
# Completed [Project #8 - Design Your Own Grid-based Framework](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap) in partial requirements of the [Microverse Curriculum](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59564673/). 💯💯💯

---

### Contributors 👨🏼‍💻
- Santiago Rueda Ortiz
- Simon Debbarma

--- 

##### General Requirements

- [x] Add descriptive README file to your repository.
- [x] Use meaningful names for your Pull Requests and add a short summary of its content.
- [x] Use descriptive commit messages.
- [x] Do not commit files that are not related to the project. Instead, add them to .gitignore file.
- [x] Do not commit inline comments. 
- [x] Use stickler for checks.

##### Other Requirements
- [x] Keep your code clean.
- [x] Remember to use semantic HTML.
- [x] Validate your HTML markup.
- [x] Use stylelint to lint CSS files.

##### Project Specific
- [x] Think about responsiveness:
- [x] breakpoint for small screens with a width of up to 720px
- [x] breakpoint for medium screens with a width in the range of 720px - 1024px
- [x] breakpoint for large screens with width above 1024px

---

# Project Status :

### CODE REVIEW

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @simonpeterdebbarma @srueda27 , 👋 You have done a great job in this project 👏. 




----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Comment by imhta** [comment]
### You have done an amazing job in building and cloning. 👏  🎉 Kudos for that

**Comment by simondebbarma** [comment]
@imhta Thanks man! We are really proud of our framework. 

We have built it with a LOT of features that other frameworks don't have. We will be building it completely over the next months, and launch it as an open source project! Keep an eye out. You can also follow the project on Twitter at https://twitter.com/outgrid_css

**Comment by imhta** [comment]
@simonpeterdebbarma  That's great. looking forward to that. Meanwhile, I did a similar thing like this check this out [css.gridy](https://imhta.github.io/cssgridy-doc/)

**Comment by simondebbarma** [comment]
@imhta Nice! I was interested to know about the CDN. I'll text you on Slack.

**Pull request merged**
